import React from "react";
import "./faq.css";
import Question from "../../components/question/Question";

const FAQData = [
  {
    question: "What types of texts can I use with TextXtract?",
    answer:
      "TextXtract can be used with a wide variety of texts, including articles, research papers, reports, and more. As long as the text is in English and can be pasted into the input box, TextXtract should be able to generate a summary.",
  },
  {
    question: "How accurate are the summaries generated by TextXtract?",
    answer:
      "The accuracy of the summaries generated by TextXtract will depend on a number of factors, including the length and complexity of the original text. However, our GPT-based summarization algorithm is designed to produce accurate and informative summaries that capture the key points of the original text.",
  },
  {
    question:
      "Can I customize the length of the summary generated by TextXtract?",
    answer:
      "Yes! TextXtract allows you to adjust the length of the summary to fit your needs. By default, summaries are set to a length of 3 sentences, but you can adjust this to be shorter or longer as needed",
  },
  {
    question: "Is my data secure when using TextXtract?",
    answer:
      " Yes, we take the security of your data very seriously. TextXtract does not store any of the text that you input into the application, and all summaries are generated on your local machine. Additionally, all data transmitted between your machine and our servers is encrypted using industry-standard security protocols to ensure that your data remains private and secure.",
  },
];

const Faq = () => (
  <div className="gpt3__features section__padding" id="faq">
    <div className="gpt3__features-heading">
      <h1 className="gradient__text">Frequently Asked Questions</h1>
      <p>Find answers to commonly asked questions about TextXtract</p>
    </div>
    <div className="gpt3__features-container">
      {FAQData.map((item, index) => (
        <Question
          question={item.question}
          answer={item.answer}
          key={item.question + index}
        />
      ))}
    </div>
  </div>
);

export default Faq;
